sudo: required
services:
  - docker

before_install:
  - docker build -t tienvv1234/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tienvv1234/react-test npm run test -- --coverage

after_success:
  - docker build -t tienvv1234/multi-client ./client
  - docker build -t tienvv1234/multi-nginx ./nginx
  - docker build -t tienvv1234/multi-server ./server
  - docker build -t tienvv1234/multi-worker ./worker
  # Login into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tienvv1234/multi-client
  - docker push tienvv1234/multi-nginx
  - docker push tienvv1234/multi-server
  - docker push tienvv1234/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-235961091445"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
